# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\zr\miketee4(1200)\ui_1080\conduit_card_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(396, 278)
        Form.setMinimumSize(QtCore.QSize(396, 278))
        Form.setMaximumSize(QtCore.QSize(396, 278))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("QWidget#widget{\n"
"    background-color:rgb(255, 255, 255);\n"
"    border-radius:30px;\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 70))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 70))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(20, 6, 19, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.conduit_card_id_l = QtWidgets.QLabel(self.widget_2)
        self.conduit_card_id_l.setMinimumSize(QtCore.QSize(150, 50))
        self.conduit_card_id_l.setMaximumSize(QtCore.QSize(150, 50))
        self.conduit_card_id_l.setStyleSheet("background-color:rgb(21, 136, 74);\n"
"color:rgb(255, 255, 255);\n"
"border-radius:25px;")
        self.conduit_card_id_l.setAlignment(QtCore.Qt.AlignCenter)
        self.conduit_card_id_l.setObjectName("conduit_card_id_l")
        self.horizontalLayout_2.addWidget(self.conduit_card_id_l)
        spacerItem = QtWidgets.QSpacerItem(170, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.conduit_card_mark_l = QtWidgets.QLabel(self.widget_2)
        self.conduit_card_mark_l.setMinimumSize(QtCore.QSize(24, 24))
        self.conduit_card_mark_l.setMaximumSize(QtCore.QSize(24, 24))
        self.conduit_card_mark_l.setStyleSheet("border-image: url(:/icon/conduit_card_mark.png);")
        self.conduit_card_mark_l.setText("")
        self.conduit_card_mark_l.setObjectName("conduit_card_mark_l")
        self.horizontalLayout_2.addWidget(self.conduit_card_mark_l)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setStyleSheet("QWidget#widget_4{\n"
"    background-color:transparent;\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.conduit_card_name_l = QtWidgets.QLabel(self.widget_4)
        self.conduit_card_name_l.setStyleSheet("color:rgb(44, 159, 97);")
        self.conduit_card_name_l.setObjectName("conduit_card_name_l")
        self.horizontalLayout_3.addWidget(self.conduit_card_name_l)
        spacerItem2 = QtWidgets.QSpacerItem(97, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 12)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_8 = QtWidgets.QWidget(self.widget_5)
        self.widget_8.setMinimumSize(QtCore.QSize(350, 0))
        self.widget_8.setMaximumSize(QtCore.QSize(350, 16777215))
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_7.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.conduit_card_title_l = QtWidgets.QLabel(self.widget_8)
        self.conduit_card_title_l.setStyleSheet("color:rgb(44, 159, 97);")
        self.conduit_card_title_l.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.conduit_card_title_l.setObjectName("conduit_card_title_l")
        self.horizontalLayout_7.addWidget(self.conduit_card_title_l)
        self.conduit_card_g_l = QtWidgets.QLabel(self.widget_8)
        self.conduit_card_g_l.setStyleSheet("color:rgb(44, 159, 97);")
        self.conduit_card_g_l.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.conduit_card_g_l.setObjectName("conduit_card_g_l")
        self.horizontalLayout_7.addWidget(self.conduit_card_g_l)
        self.horizontalLayout_4.addWidget(self.widget_8)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget_3)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 11)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_7 = QtWidgets.QWidget(self.widget_6)
        self.widget_7.setMinimumSize(QtCore.QSize(350, 46))
        self.widget_7.setMaximumSize(QtCore.QSize(350, 46))
        self.widget_7.setStyleSheet("QWidget#widget_7{\n"
"    background-color:rgb(44, 159, 97);\n"
"    color:white;\n"
"    border-radius:23px;\n"
"    \n"
"}")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_6.setContentsMargins(-1, 7, 10, 8)
        self.horizontalLayout_6.setSpacing(11)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.widget_7)
        self.label.setMinimumSize(QtCore.QSize(32, 32))
        self.label.setMaximumSize(QtCore.QSize(32, 32))
        self.label.setStyleSheet("border-image: url(:/icon/icon_conduit_card_clock_white.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget_7)
        self.label_2.setStyleSheet("color:white;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.l_date = QtWidgets.QLabel(self.widget_7)
        self.l_date.setStyleSheet("color:white;")
        self.l_date.setAlignment(QtCore.Qt.AlignCenter)
        self.l_date.setObjectName("l_date")
        self.horizontalLayout_6.addWidget(self.l_date)
        self.horizontalLayout_5.addWidget(self.widget_7)
        self.verticalLayout_2.addWidget(self.widget_6)
        self.verticalLayout.addWidget(self.widget_3)
        self.horizontalLayout.addWidget(self.widget)

        # ★ 在 1# 后面加一个“未被使用(X)”图标位，默认隐藏
        self.conduit_unused_x = QtWidgets.QLabel(self.widget_2)
        self.conduit_unused_x.setMinimumSize(QtCore.QSize(60, 60))
        self.conduit_unused_x.setMaximumSize(QtCore.QSize(100, 100))
        self.conduit_unused_x.setStyleSheet("border-image: url(:/icon/icon_null.png);")
        self.conduit_unused_x.setToolTip("该材料未被任何配方使用")
        self.conduit_unused_x.setVisible(False)  # 等主程序判定后再显示
        # 插入到 ID 右侧
        self.horizontalLayout_2.insertWidget(1, self.conduit_unused_x)

        self.conduit_unused_x = QtWidgets.QLabel(self.widget_2)
        self.conduit_unused_x.setMinimumSize(QtCore.QSize(60, 60))
        self.conduit_unused_x.setMaximumSize(QtCore.QSize(100, 100))
        self.conduit_unused_x.setStyleSheet("border-image: url(:/icon/icon_null.png);")
        self.conduit_unused_x.setToolTip("该材料未被任何配方使用")
        self.conduit_unused_x.setObjectName("conduit_unused_x")   # ★ 新增：便于 findChild
        self.conduit_unused_x.setVisible(False)                   # 默认隐藏
        self.horizontalLayout_2.insertWidget(1, self.conduit_unused_x)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.conduit_card_id_l.setText(_translate("Form", "001"))
        self.conduit_card_name_l.setText(_translate("Form", "红茶"))
        self.conduit_card_title_l.setText(_translate("Form", "剩余量"))
        self.conduit_card_g_l.setText(_translate("Form", "1234g"))
        self.label_2.setText(_translate("Form", "到期时间"))
        self.l_date.setText(_translate("Form", "14:59"))
import drawable_rc
