# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\zr\miketee4(1200)\ui_1080\conduit_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        Form.setMinimumSize(QtCore.QSize(1920, 1080))
        Form.setMaximumSize(QtCore.QSize(1920, 1080))
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.main_widget = QtWidgets.QWidget(Form)
        self.main_widget.setMaximumSize(QtCore.QSize(1920, 1080))
        self.main_widget.setStyleSheet("QWidget#main_widget{\n"
"    background-color: rgba(255, 255, 255, 150);\n"
"}\n"
"")
        self.main_widget.setObjectName("main_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(550, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.widget_8 = QtWidgets.QWidget(self.main_widget)
        self.widget_8.setMaximumSize(QtCore.QSize(1920, 1080))
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.widget = QtWidgets.QWidget(self.widget_8)
        self.widget.setMinimumSize(QtCore.QSize(866, 402))
        self.widget.setMaximumSize(QtCore.QSize(866, 402))
        self.widget.setStyleSheet("QWidget#widget{\n"
"    border-image: url(:/icon/conduit_dialog_background.png);\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 21, 27, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(690, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.dialog_close_btn = QtWidgets.QPushButton(self.widget_2)
        self.dialog_close_btn.setMinimumSize(QtCore.QSize(40, 40))
        self.dialog_close_btn.setMaximumSize(QtCore.QSize(40, 40))
        self.dialog_close_btn.setStyleSheet("border-image:url(:/icon/conduit_dialog_close_btn.png);")
        self.dialog_close_btn.setText("")
        self.dialog_close_btn.setObjectName("dialog_close_btn")
        self.horizontalLayout_2.addWidget(self.dialog_close_btn)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_7 = QtWidgets.QWidget(self.widget)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout.setContentsMargins(0, 0, 0, 46)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget_7)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setContentsMargins(100, 0, 100, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.dialog_name_1 = QtWidgets.QLabel(self.widget_3)
        self.dialog_name_1.setMinimumSize(QtCore.QSize(75, 50))
        self.dialog_name_1.setMaximumSize(QtCore.QSize(75, 50))
        self.dialog_name_1.setStyleSheet("color:rgb(44, 159, 97);")
        self.dialog_name_1.setObjectName("dialog_name_1")
        self.horizontalLayout_4.addWidget(self.dialog_name_1)
        self.dialog_config_1 = QtWidgets.QLabel(self.widget_3)
        self.dialog_config_1.setMinimumSize(QtCore.QSize(136, 50))
        self.dialog_config_1.setMaximumSize(QtCore.QSize(136, 50))
        self.dialog_config_1.setStyleSheet("color:rgb(51, 51, 51);")
        self.dialog_config_1.setObjectName("dialog_config_1")
        self.horizontalLayout_4.addWidget(self.dialog_config_1)
        self.dialog_name_2 = QtWidgets.QLabel(self.widget_3)
        self.dialog_name_2.setMinimumSize(QtCore.QSize(75, 50))
        self.dialog_name_2.setMaximumSize(QtCore.QSize(75, 50))
        self.dialog_name_2.setStyleSheet("color:rgb(44, 159, 97);")
        self.dialog_name_2.setObjectName("dialog_name_2")
        self.horizontalLayout_4.addWidget(self.dialog_name_2)
        self.dialog_config_2 = QtWidgets.QLabel(self.widget_3)
        self.dialog_config_2.setMinimumSize(QtCore.QSize(136, 50))
        self.dialog_config_2.setMaximumSize(QtCore.QSize(136, 50))
        self.dialog_config_2.setStyleSheet("color:rgb(51, 51, 51);")
        self.dialog_config_2.setObjectName("dialog_config_2")
        self.horizontalLayout_4.addWidget(self.dialog_config_2)
        self.dialog_name_3 = QtWidgets.QLabel(self.widget_3)
        self.dialog_name_3.setMinimumSize(QtCore.QSize(75, 50))
        self.dialog_name_3.setMaximumSize(QtCore.QSize(75, 50))
        self.dialog_name_3.setStyleSheet("color:rgb(44, 159, 97);")
        self.dialog_name_3.setObjectName("dialog_name_3")
        self.horizontalLayout_4.addWidget(self.dialog_name_3)
        self.dialog_config_3 = QtWidgets.QLineEdit(self.widget_3)
        self.dialog_config_3.setMinimumSize(QtCore.QSize(136, 50))
        self.dialog_config_3.setMaximumSize(QtCore.QSize(136, 50))
        self.dialog_config_3.setStyleSheet("background-color:Transparent;\n"
"border: 1px solid Transparent;")
        self.dialog_config_3.setObjectName("dialog_config_3")
        self.horizontalLayout_4.addWidget(self.dialog_config_3)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_5 = QtWidgets.QWidget(self.widget_7)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setContentsMargins(100, 0, 100, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.dialog_name_4 = QtWidgets.QLabel(self.widget_5)
        self.dialog_name_4.setMinimumSize(QtCore.QSize(75, 50))
        self.dialog_name_4.setMaximumSize(QtCore.QSize(75, 50))
        self.dialog_name_4.setStyleSheet("color:rgb(44, 159, 97);")
        self.dialog_name_4.setObjectName("dialog_name_4")
        self.horizontalLayout_5.addWidget(self.dialog_name_4)
        self.dialog_config_4 = QtWidgets.QComboBox(self.widget_5)
        self.dialog_config_4.setMinimumSize(QtCore.QSize(136, 50))
        self.dialog_config_4.setMaximumSize(QtCore.QSize(136, 50))
        self.dialog_config_4.setStyleSheet("    background-color:white;\n"
"    border: 1px solid white;\n"
"    border-radius:33px;\n"
"    color:rgb(44, 159, 97);")
        self.dialog_config_4.setObjectName("dialog_config_4")
        self.horizontalLayout_5.addWidget(self.dialog_config_4)
        self.dialog_name_5 = QtWidgets.QLabel(self.widget_5)
        self.dialog_name_5.setMinimumSize(QtCore.QSize(75, 50))
        self.dialog_name_5.setMaximumSize(QtCore.QSize(75, 50))
        self.dialog_name_5.setStyleSheet("color:rgb(44, 159, 97);")
        self.dialog_name_5.setObjectName("dialog_name_5")
        self.horizontalLayout_5.addWidget(self.dialog_name_5)
        self.dialog_config_5 = QtWidgets.QLabel(self.widget_5)
        self.dialog_config_5.setMinimumSize(QtCore.QSize(136, 50))
        self.dialog_config_5.setMaximumSize(QtCore.QSize(136, 50))
        self.dialog_config_5.setStyleSheet("color:rgb(51, 51, 51);")
        self.dialog_config_5.setObjectName("dialog_config_5")
        self.horizontalLayout_5.addWidget(self.dialog_config_5)
        self.dialog_name_7 = QtWidgets.QLabel(self.widget_5)
        self.dialog_name_7.setMinimumSize(QtCore.QSize(115, 50))
        self.dialog_name_7.setMaximumSize(QtCore.QSize(115, 50))
        self.dialog_name_7.setStyleSheet("color:rgb(44, 159, 97);")
        self.dialog_name_7.setObjectName("dialog_name_7")
        self.horizontalLayout_5.addWidget(self.dialog_name_7)
        self.dialog_config_7 = QtWidgets.QComboBox(self.widget_5)
        self.dialog_config_7.setMinimumSize(QtCore.QSize(96, 50))
        self.dialog_config_7.setMaximumSize(QtCore.QSize(96, 50))
        self.dialog_config_7.setStyleSheet("    background-color:white;\n"
"    border: 1px solid white;\n"
"    border-radius:33px;\n"
"    color:rgb(44, 159, 97);")
        self.dialog_config_7.setObjectName("dialog_config_7")
        self.horizontalLayout_5.addWidget(self.dialog_config_7)
        self.verticalLayout.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget_7)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_6.setContentsMargins(100, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.dialog_name_6 = QtWidgets.QLabel(self.widget_6)
        self.dialog_name_6.setMinimumSize(QtCore.QSize(75, 50))
        self.dialog_name_6.setMaximumSize(QtCore.QSize(75, 50))
        self.dialog_name_6.setStyleSheet("color:rgb(44, 159, 97);")
        self.dialog_name_6.setObjectName("dialog_name_6")
        self.horizontalLayout_6.addWidget(self.dialog_name_6)
        self.dialog_config_6 = QtWidgets.QLabel(self.widget_6)
        self.dialog_config_6.setMinimumSize(QtCore.QSize(0, 50))
        self.dialog_config_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.dialog_config_6.setStyleSheet("color:rgb(51, 51, 51);")
        self.dialog_config_6.setObjectName("dialog_config_6")
        self.horizontalLayout_6.addWidget(self.dialog_config_6)
        self.verticalLayout.addWidget(self.widget_6)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setContentsMargins(105, 0, 103, 34)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.conduit_cancel_btn = QtWidgets.QPushButton(self.widget_4)
        self.conduit_cancel_btn.setMinimumSize(QtCore.QSize(250, 66))
        self.conduit_cancel_btn.setMaximumSize(QtCore.QSize(250, 66))
        self.conduit_cancel_btn.setStyleSheet("QPushButton#conduit_cancel_btn{\n"
"    background-color:rgb(243, 243, 243);\n"
"    border: 1px solid white;\n"
"    border-radius:33px;\n"
"    color:rgb(44, 159, 97);\n"
"}\n"
"QPushButton#conduit_cancel_btn:pressed{\n"
"    background-color:red;\n"
"    border: 1px solid rgb(44, 159, 97);\n"
"    border-radius:33px;\n"
"    color:white;\n"
"}")
        self.conduit_cancel_btn.setObjectName("conduit_cancel_btn")
        self.horizontalLayout_3.addWidget(self.conduit_cancel_btn)
        spacerItem3 = QtWidgets.QSpacerItem(55, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.conduit_save_btn = QtWidgets.QPushButton(self.widget_4)
        self.conduit_save_btn.setMinimumSize(QtCore.QSize(250, 66))
        self.conduit_save_btn.setMaximumSize(QtCore.QSize(250, 66))
        self.conduit_save_btn.setStyleSheet("QPushButton#conduit_save_btn{\n"
"    background-color:rgb(44, 159, 97);\n"
"    border: 1px solid rgb(44, 159, 97);\n"
"    border-radius:33px;\n"
"    color:white;\n"
"}\n"
"QPushButton#conduit_save_btn:pressed{\n"
"    background-color:white;\n"
"    border: 1px solid white;\n"
"    border-radius:33px;\n"
"    color:rgb(44, 159, 97);\n"
"}")
        self.conduit_save_btn.setObjectName("conduit_save_btn")
        self.horizontalLayout_3.addWidget(self.conduit_save_btn)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.verticalLayout_3.addWidget(self.widget)
        spacerItem4 = QtWidgets.QSpacerItem(20, 312, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout.addWidget(self.widget_8)
        spacerItem5 = QtWidgets.QSpacerItem(550, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.horizontalLayout_7.addWidget(self.main_widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.dialog_name_1.setText(_translate("Form", "管道："))
        self.dialog_config_1.setText(_translate("Form", "A"))
        self.dialog_name_2.setText(_translate("Form", "类型："))
        self.dialog_config_2.setText(_translate("Form", "茶基底"))
        self.dialog_name_3.setText(_translate("Form", "名称："))
        self.dialog_name_4.setText(_translate("Form", "速度："))
        self.dialog_name_5.setText(_translate("Form", "余量："))
        self.dialog_config_5.setText(_translate("Form", "1234g"))
        self.dialog_name_7.setText(_translate("Form", "优先级："))
        self.dialog_name_6.setText(_translate("Form", "应用："))
        self.dialog_config_6.setText(_translate("Form", "柠檬绿茶、草莓啵啵、XXX"))
        self.conduit_cancel_btn.setText(_translate("Form", "取消"))
        self.conduit_save_btn.setText(_translate("Form", "保存"))
import drawable_rc
