# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\zr\miketee4(1200)\ui_1080\item_setting_local_tee_record_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1233, 73)
        Form.setMinimumSize(QtCore.QSize(0, 73))
        Form.setMaximumSize(QtCore.QSize(16777215, 73))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(0, 73))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 73))
        self.widget.setStyleSheet("QWidget#widget{\n"
"    background-color:rgba(239, 255, 247, 1);\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_78 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_78.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_78.setSpacing(0)
        self.horizontalLayout_78.setObjectName("horizontalLayout_78")
        self.l_1 = QtWidgets.QLabel(self.widget)
        self.l_1.setStyleSheet("color:rgba(102, 102, 102, 1);")
        self.l_1.setAlignment(QtCore.Qt.AlignCenter)
        self.l_1.setObjectName("l_1")
        self.horizontalLayout_78.addWidget(self.l_1)
        self.l_2 = QtWidgets.QLabel(self.widget)
        self.l_2.setStyleSheet("color:rgba(102, 102, 102, 1);")
        self.l_2.setAlignment(QtCore.Qt.AlignCenter)
        self.l_2.setObjectName("l_2")
        self.horizontalLayout_78.addWidget(self.l_2)
        self.l_3 = QtWidgets.QLabel(self.widget)
        self.l_3.setStyleSheet("color:rgba(102, 102, 102, 1);")
        self.l_3.setAlignment(QtCore.Qt.AlignCenter)
        self.l_3.setObjectName("l_3")
        self.horizontalLayout_78.addWidget(self.l_3)
        self.l_4 = QtWidgets.QLabel(self.widget)
        self.l_4.setStyleSheet("color:rgba(102, 102, 102, 1);")
        self.l_4.setAlignment(QtCore.Qt.AlignCenter)
        self.l_4.setObjectName("l_4")
        self.horizontalLayout_78.addWidget(self.l_4)
        self.l_5 = QtWidgets.QLabel(self.widget)
        self.l_5.setMinimumSize(QtCore.QSize(0, 80))
        self.l_5.setMaximumSize(QtCore.QSize(16777215, 80))
        self.l_5.setStyleSheet("color:rgba(102, 102, 102, 1);")
        self.l_5.setAlignment(QtCore.Qt.AlignCenter)
        self.l_5.setObjectName("l_5")
        self.horizontalLayout_78.addWidget(self.l_5)
        self.horizontalLayout_78.setStretch(0, 3)
        self.horizontalLayout_78.setStretch(1, 3)
        self.horizontalLayout_78.setStretch(2, 3)
        self.horizontalLayout_78.setStretch(3, 7)
        self.horizontalLayout_78.setStretch(4, 3)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.l_1.setText(_translate("Form", "序号"))
        self.l_2.setText(_translate("Form", "取茶号"))
        self.l_3.setText(_translate("Form", "茶品名称"))
        self.l_4.setText(_translate("Form", "订单时间"))
        self.l_5.setText(_translate("Form", "出茶状态"))
