# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\zr\miketee4(1200)\ui_1080\item_screen_conduit_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(267, 189)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("QWidget#widget{\n"
"    background-color:white;\n"
"    border-radius:24px;\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(17, 17, 17, 17)
        self.horizontalLayout_2.setSpacing(25)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(44, 155))
        self.widget_2.setMaximumSize(QtCore.QSize(44, 155))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setMinimumSize(QtCore.QSize(164, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(164, 16777215))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.l_conduit = QtWidgets.QLabel(self.widget_3)
        self.l_conduit.setStyleSheet("color:rgba(44, 159, 97, 1);")
        self.l_conduit.setObjectName("l_conduit")
        self.verticalLayout.addWidget(self.l_conduit)
        self.l_name = QtWidgets.QLabel(self.widget_3)
        self.l_name.setStyleSheet("color:rgba(44, 159, 97, 1);")
        self.l_name.setObjectName("l_name")
        self.verticalLayout.addWidget(self.l_name)
        self.l_margin = QtWidgets.QLabel(self.widget_3)
        self.l_margin.setStyleSheet("color:rgba(44, 159, 97, 1);")
        self.l_margin.setObjectName("l_margin")
        self.verticalLayout.addWidget(self.l_margin)
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setStyleSheet("QWidget#widget_4{\n"
"    background-color:white;\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(12)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setMinimumSize(QtCore.QSize(24, 24))
        self.label_4.setMaximumSize(QtCore.QSize(24, 24))
        self.label_4.setStyleSheet("border-image: url(:/icon/icon_second_screen_clock.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.l_time = QtWidgets.QLabel(self.widget_4)
        self.l_time.setStyleSheet("color:rgba(44, 159, 97, 1);")
        self.l_time.setObjectName("l_time")
        self.horizontalLayout_3.addWidget(self.l_time)
        self.verticalLayout.addWidget(self.widget_4)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.l_conduit.setText(_translate("Form", "TextLabel"))
        self.l_name.setText(_translate("Form", "TextLabel"))
        self.l_margin.setText(_translate("Form", "TextLabel"))
        self.l_time.setText(_translate("Form", "TextLabel"))
import drawable_rc
