# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_1080\ui_language_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(4000, 2000))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 100, 1391, 921))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background-color: #f8f9fa;          /* 浅灰背景 */\n"
"    border: 2px solid #d0d7de;           /* 外边框 */\n"
"    border-radius: 18px;                  /* 圆角 */\n"
"    margin-top: 12px;                      /* 为标题留出空间（标题本身会占据位置） */\n"
"    padding-top: 8px;                      /* 内边距，避免内容紧贴边框 */\n"
"    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.15);  /* 外阴影，使整体凸起 */\n"
"}\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(30, 140, 611, 91))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(25)
        self.radioButton.setFont(font)
        self.radioButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.radioButton.setAutoFillBackground(False)
        self.radioButton.setStyleSheet("/* 所有 QRadioButton 的基础样式 */\n"
"QRadioButton {\n"
"    background-color: #f0f0f0;        /* 未选中时的背景色 */\n"
"    color: #333333;                    /* 未选中时的文字颜色 */\n"
"    border: 1px solid #cccccc;          /* 边框 */\n"
"    border-radius: 15px;                /* 圆角，可根据高度调整 */\n"
"    padding: 5px 15px;                  /* 内边距，增大点击区域 */\n"
"    spacing: 5px;                        \n"
"}\n"
"\n"
"\n"
"/* 选中时的样式 */\n"
"QRadioButton:checked {\n"
"    background-color: #4CAF50;          /* 绿色背景 */\n"
"    color: white;                        /* 白色文字 */\n"
"    border: 1px solid #27ae60;           \n"
"}\n"
"\n"
"/* 悬停效果 */\n"
"QRadioButton:hover {\n"
"    background-color: #e0e0e0;\n"
"}\n"
"QRadioButton:checked:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 0px;                       /* 隐藏默认的指示器（小圆圈） */\n"
"    height: 0px;\n"
"}")
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(30, 460, 611, 91))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(25)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.radioButton_3.setAutoFillBackground(False)
        self.radioButton_3.setStyleSheet("/* 所有 QRadioButton 的基础样式 */\n"
"QRadioButton {\n"
"    background-color: #f0f0f0;        /* 未选中时的背景色 */\n"
"    color: #333333;                    /* 未选中时的文字颜色 */\n"
"    border: 1px solid #cccccc;          /* 边框 */\n"
"    border-radius: 15px;                /* 圆角，可根据高度调整 */\n"
"    padding: 5px 15px;                  /* 内边距，增大点击区域 */\n"
"    spacing: 5px;                        \n"
"}\n"
"\n"
"\n"
"/* 选中时的样式 */\n"
"QRadioButton:checked {\n"
"    background-color: #4CAF50;          /* 绿色背景 */\n"
"    color: white;                        /* 白色文字 */\n"
"    border: 1px solid #27ae60;           \n"
"}\n"
"\n"
"/* 悬停效果 */\n"
"QRadioButton:hover {\n"
"    background-color: #e0e0e0;\n"
"}\n"
"QRadioButton:checked:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 0px;                       /* 隐藏默认的指示器（小圆圈） */\n"
"    height: 0px;\n"
"}")
        self.radioButton_3.setObjectName("radioButton_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(750, 60, 581, 341))
        self.label_2.setStyleSheet("border-image: url(:/icon/language_illustration.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(30, 80, 481, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(27)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 291, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_11.setGeometry(QtCore.QRect(30, 780, 611, 91))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(25)
        self.radioButton_11.setFont(font)
        self.radioButton_11.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.radioButton_11.setAutoFillBackground(False)
        self.radioButton_11.setStyleSheet("/* 所有 QRadioButton 的基础样式 */\n"
"QRadioButton {\n"
"    background-color: #f0f0f0;        /* 未选中时的背景色 */\n"
"    color: #333333;                    /* 未选中时的文字颜色 */\n"
"    border: 1px solid #cccccc;          /* 边框 */\n"
"    border-radius: 15px;                /* 圆角，可根据高度调整 */\n"
"    padding: 5px 15px;                  /* 内边距，增大点击区域 */\n"
"    spacing: 5px;                        \n"
"}\n"
"\n"
"\n"
"/* 选中时的样式 */\n"
"QRadioButton:checked {\n"
"    background-color: #4CAF50;          /* 绿色背景 */\n"
"    color: white;                        /* 白色文字 */\n"
"    border: 1px solid #27ae60;           \n"
"}\n"
"\n"
"/* 悬停效果 */\n"
"QRadioButton:hover {\n"
"    background-color: #e0e0e0;\n"
"}\n"
"QRadioButton:checked:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 0px;                       /* 隐藏默认的指示器（小圆圈） */\n"
"    height: 0px;\n"
"}")
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_8.setGeometry(QtCore.QRect(30, 300, 611, 91))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(25)
        self.radioButton_8.setFont(font)
        self.radioButton_8.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.radioButton_8.setAutoFillBackground(False)
        self.radioButton_8.setStyleSheet("/* 所有 QRadioButton 的基础样式 */\n"
"QRadioButton {\n"
"    background-color: #f0f0f0;        /* 未选中时的背景色 */\n"
"    color: #333333;                    /* 未选中时的文字颜色 */\n"
"    border: 1px solid #cccccc;          /* 边框 */\n"
"    border-radius: 15px;                /* 圆角，可根据高度调整 */\n"
"    padding: 5px 15px;                  /* 内边距，增大点击区域 */\n"
"    spacing: 5px;                        \n"
"}\n"
"\n"
"\n"
"/* 选中时的样式 */\n"
"QRadioButton:checked {\n"
"    background-color: #4CAF50;          /* 绿色背景 */\n"
"    color: white;                        /* 白色文字 */\n"
"    border: 1px solid #27ae60;           \n"
"}\n"
"\n"
"/* 悬停效果 */\n"
"QRadioButton:hover {\n"
"    background-color: #e0e0e0;\n"
"}\n"
"QRadioButton:checked:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 0px;                       /* 隐藏默认的指示器（小圆圈） */\n"
"    height: 0px;\n"
"}")
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_9.setGeometry(QtCore.QRect(30, 620, 611, 91))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(25)
        self.radioButton_9.setFont(font)
        self.radioButton_9.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.radioButton_9.setAutoFillBackground(False)
        self.radioButton_9.setStyleSheet("/* 所有 QRadioButton 的基础样式 */\n"
"QRadioButton {\n"
"    background-color: #f0f0f0;        /* 未选中时的背景色 */\n"
"    color: #333333;                    /* 未选中时的文字颜色 */\n"
"    border: 1px solid #cccccc;          /* 边框 */\n"
"    border-radius: 15px;                /* 圆角，可根据高度调整 */\n"
"    padding: 5px 15px;                  /* 内边距，增大点击区域 */\n"
"    spacing: 5px;                        \n"
"}\n"
"\n"
"\n"
"/* 选中时的样式 */\n"
"QRadioButton:checked {\n"
"    background-color: #4CAF50;          /* 绿色背景 */\n"
"    color: white;                        /* 白色文字 */\n"
"    border: 1px solid #27ae60;           \n"
"}\n"
"\n"
"/* 悬停效果 */\n"
"QRadioButton:hover {\n"
"    background-color: #e0e0e0;\n"
"}\n"
"QRadioButton:checked:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 0px;                       /* 隐藏默认的指示器（小圆圈） */\n"
"    height: 0px;\n"
"}")
        self.radioButton_9.setObjectName("radioButton_9")
        self.pushButton_language_pply = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_language_pply.setGeometry(QtCore.QRect(900, 440, 351, 91))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(36)
        font.setBold(False)
        self.pushButton_language_pply.setFont(font)
        self.pushButton_language_pply.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    padding: 5px 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #27ae60;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1e8449;\n"
"}")
        self.pushButton_language_pply.setObjectName("pushButton_language_pply")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 0, 1391, 91))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    background-color: #f8f9fa;          /* 浅灰背景 */\n"
"    border: 2px solid #d0d7de;           /* 外边框 */\n"
"    border-radius: 12px;                  /* 圆角 */\n"
"    margin-top: 5px;                     \n"
"    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.15);  /* 外阴影，使整体凸起 */\n"
"}\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 60, 60))
        self.label_7.setMinimumSize(QtCore.QSize(41, 41))
        self.label_7.setMaximumSize(QtCore.QSize(60, 60))
        self.label_7.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("\n"
"border-image: url(:/icon/icon_back.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(70, 20, 192, 48))
        self.label.setMinimumSize(QtCore.QSize(181, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(36)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton.setText(_translate("MainWindow", "简体中文"))
        self.radioButton_3.setText(_translate("MainWindow", "English"))
        self.label_5.setText(_translate("MainWindow", "选择一种语言应用于整个界面"))
        self.label_4.setText(_translate("MainWindow", "选择界面语言"))
        self.radioButton_11.setText(_translate("MainWindow", "한국어"))
        self.radioButton_8.setText(_translate("MainWindow", "繁體中文"))
        self.radioButton_9.setText(_translate("MainWindow", "日本語"))
        self.pushButton_language_pply.setText(_translate("MainWindow", "应用"))
        self.label.setText(_translate("MainWindow", "语言选择"))
import drawable_rc
