# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_language_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    background-color: #f8f9fa;          /* 浅灰背景 */\n"
"    border: 2px solid #d0d7de;           /* 外边框 */\n"
"    border-radius: 12px;                  /* 圆角 */\n"
"    margin-top: 5px;                     \n"
"    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.15);  /* 外阴影，使整体凸起 */\n"
"}\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setMinimumSize(QtCore.QSize(41, 41))
        self.label_7.setMaximumSize(QtCore.QSize(41, 41))
        self.label_7.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_7.setStyleSheet("\n"
"border-image: url(:/icon/icon_back.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setMinimumSize(QtCore.QSize(181, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background-color: #f8f9fa;          /* 浅灰背景 */\n"
"    border: 2px solid #d0d7de;           /* 外边框 */\n"
"    border-radius: 18px;                  /* 圆角 */\n"
"    margin-top: 12px;                      /* 为标题留出空间（标题本身会占据位置） */\n"
"    padding-top: 8px;                      /* 内边距，避免内容紧贴边框 */\n"
"    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.15);  /* 外阴影，使整体凸起 */\n"
"}\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(40)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setMinimumSize(QtCore.QSize(331, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.radioButton.setFont(font)
        self.radioButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton.setAutoFillBackground(False)
        self.radioButton.setStyleSheet("/* 所有 QRadioButton 的基础样式 */\n"
"QRadioButton {\n"
"    background-color: #f0f0f0;        /* 未选中时的背景色 */\n"
"    color: #333333;                    /* 未选中时的文字颜色 */\n"
"    border: 1px solid #cccccc;          /* 边框 */\n"
"    border-radius: 15px;                /* 圆角，可根据高度调整 */\n"
"    padding: 5px 15px;                  /* 内边距，增大点击区域 */\n"
"    spacing: 5px;                        \n"
"}\n"
"\n"
"\n"
"/* 选中时的样式 */\n"
"QRadioButton:checked {\n"
"    background-color: #4CAF50;          /* 绿色背景 */\n"
"    color: white;                        /* 白色文字 */\n"
"    border: 1px solid #27ae60;           \n"
"}\n"
"\n"
"/* 悬停效果 */\n"
"QRadioButton:hover {\n"
"    background-color: #e0e0e0;\n"
"}\n"
"QRadioButton:checked:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 0px;                       /* 隐藏默认的指示器（小圆圈） */\n"
"    height: 0px;\n"
"}")
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        spacerItem = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_8.setMinimumSize(QtCore.QSize(331, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.radioButton_8.setFont(font)
        self.radioButton_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_8.setAutoFillBackground(False)
        self.radioButton_8.setStyleSheet("/* 所有 QRadioButton 的基础样式 */\n"
"QRadioButton {\n"
"    background-color: #f0f0f0;        /* 未选中时的背景色 */\n"
"    color: #333333;                    /* 未选中时的文字颜色 */\n"
"    border: 1px solid #cccccc;          /* 边框 */\n"
"    border-radius: 15px;                /* 圆角，可根据高度调整 */\n"
"    padding: 5px 15px;                  /* 内边距，增大点击区域 */\n"
"    spacing: 5px;                        \n"
"}\n"
"\n"
"\n"
"/* 选中时的样式 */\n"
"QRadioButton:checked {\n"
"    background-color: #4CAF50;          /* 绿色背景 */\n"
"    color: white;                        /* 白色文字 */\n"
"    border: 1px solid #27ae60;           \n"
"}\n"
"\n"
"/* 悬停效果 */\n"
"QRadioButton:hover {\n"
"    background-color: #e0e0e0;\n"
"}\n"
"QRadioButton:checked:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 0px;                       /* 隐藏默认的指示器（小圆圈） */\n"
"    height: 0px;\n"
"}")
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout.addWidget(self.radioButton_8)
        spacerItem1 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setMinimumSize(QtCore.QSize(161, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_3.setAutoFillBackground(False)
        self.radioButton_3.setStyleSheet("/* 所有 QRadioButton 的基础样式 */\n"
"QRadioButton {\n"
"    background-color: #f0f0f0;        /* 未选中时的背景色 */\n"
"    color: #333333;                    /* 未选中时的文字颜色 */\n"
"    border: 1px solid #cccccc;          /* 边框 */\n"
"    border-radius: 15px;                /* 圆角，可根据高度调整 */\n"
"    padding: 5px 15px;                  /* 内边距，增大点击区域 */\n"
"    spacing: 5px;                        \n"
"}\n"
"\n"
"\n"
"/* 选中时的样式 */\n"
"QRadioButton:checked {\n"
"    background-color: #4CAF50;          /* 绿色背景 */\n"
"    color: white;                        /* 白色文字 */\n"
"    border: 1px solid #27ae60;           \n"
"}\n"
"\n"
"/* 悬停效果 */\n"
"QRadioButton:hover {\n"
"    background-color: #e0e0e0;\n"
"}\n"
"QRadioButton:checked:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 0px;                       /* 隐藏默认的指示器（小圆圈） */\n"
"    height: 0px;\n"
"}")
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.radioButton_3)
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_9.setMinimumSize(QtCore.QSize(161, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.radioButton_9.setFont(font)
        self.radioButton_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_9.setAutoFillBackground(False)
        self.radioButton_9.setStyleSheet("/* 所有 QRadioButton 的基础样式 */\n"
"QRadioButton {\n"
"    background-color: #f0f0f0;        /* 未选中时的背景色 */\n"
"    color: #333333;                    /* 未选中时的文字颜色 */\n"
"    border: 1px solid #cccccc;          /* 边框 */\n"
"    border-radius: 15px;                /* 圆角，可根据高度调整 */\n"
"    padding: 5px 15px;                  /* 内边距，增大点击区域 */\n"
"    spacing: 5px;                        \n"
"}\n"
"\n"
"\n"
"/* 选中时的样式 */\n"
"QRadioButton:checked {\n"
"    background-color: #4CAF50;          /* 绿色背景 */\n"
"    color: white;                        /* 白色文字 */\n"
"    border: 1px solid #27ae60;           \n"
"}\n"
"\n"
"/* 悬停效果 */\n"
"QRadioButton:hover {\n"
"    background-color: #e0e0e0;\n"
"}\n"
"QRadioButton:checked:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 0px;                       /* 隐藏默认的指示器（小圆圈） */\n"
"    height: 0px;\n"
"}")
        self.radioButton_9.setObjectName("radioButton_9")
        self.horizontalLayout.addWidget(self.radioButton_9)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_11.setMinimumSize(QtCore.QSize(161, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.radioButton_11.setFont(font)
        self.radioButton_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_11.setAutoFillBackground(False)
        self.radioButton_11.setStyleSheet("/* 所有 QRadioButton 的基础样式 */\n"
"QRadioButton {\n"
"    background-color: #f0f0f0;        /* 未选中时的背景色 */\n"
"    color: #333333;                    /* 未选中时的文字颜色 */\n"
"    border: 1px solid #cccccc;          /* 边框 */\n"
"    border-radius: 15px;                /* 圆角，可根据高度调整 */\n"
"    padding: 5px 15px;                  /* 内边距，增大点击区域 */\n"
"    spacing: 5px;                        \n"
"}\n"
"\n"
"\n"
"/* 选中时的样式 */\n"
"QRadioButton:checked {\n"
"    background-color: #4CAF50;          /* 绿色背景 */\n"
"    color: white;                        /* 白色文字 */\n"
"    border: 1px solid #27ae60;           \n"
"}\n"
"\n"
"/* 悬停效果 */\n"
"QRadioButton:hover {\n"
"    background-color: #e0e0e0;\n"
"}\n"
"QRadioButton:checked:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 0px;                       /* 隐藏默认的指示器（小圆圈） */\n"
"    height: 0px;\n"
"}")
        self.radioButton_11.setObjectName("radioButton_11")
        self.horizontalLayout_2.addWidget(self.radioButton_11)
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_10.setMinimumSize(QtCore.QSize(161, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.radioButton_10.setFont(font)
        self.radioButton_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_10.setAutoFillBackground(False)
        self.radioButton_10.setStyleSheet("/* 所有 QRadioButton 的基础样式 */\n"
"QRadioButton {\n"
"    background-color: #f0f0f0;        /* 未选中时的背景色 */\n"
"    color: #333333;                    /* 未选中时的文字颜色 */\n"
"    border: 1px solid #cccccc;          /* 边框 */\n"
"    border-radius: 15px;                /* 圆角，可根据高度调整 */\n"
"    padding: 5px 15px;                  /* 内边距，增大点击区域 */\n"
"    spacing: 5px;                        \n"
"}\n"
"\n"
"\n"
"/* 选中时的样式 */\n"
"QRadioButton:checked {\n"
"    background-color: #4CAF50;          /* 绿色背景 */\n"
"    color: white;                        /* 白色文字 */\n"
"    border: 1px solid #27ae60;           \n"
"}\n"
"\n"
"/* 悬停效果 */\n"
"QRadioButton:hover {\n"
"    background-color: #e0e0e0;\n"
"}\n"
"QRadioButton:checked:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 0px;                       /* 隐藏默认的指示器（小圆圈） */\n"
"    height: 0px;\n"
"}")
        self.radioButton_10.setObjectName("radioButton_10")
        self.horizontalLayout_2.addWidget(self.radioButton_10)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_12.setMinimumSize(QtCore.QSize(161, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.radioButton_12.setFont(font)
        self.radioButton_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_12.setAutoFillBackground(False)
        self.radioButton_12.setStyleSheet("/* 所有 QRadioButton 的基础样式 */\n"
"QRadioButton {\n"
"    background-color: #f0f0f0;        /* 未选中时的背景色 */\n"
"    color: #333333;                    /* 未选中时的文字颜色 */\n"
"    border: 1px solid #cccccc;          /* 边框 */\n"
"    border-radius: 15px;                /* 圆角，可根据高度调整 */\n"
"    padding: 5px 15px;                  /* 内边距，增大点击区域 */\n"
"    spacing: 5px;                        \n"
"}\n"
"\n"
"\n"
"/* 选中时的样式 */\n"
"QRadioButton:checked {\n"
"    background-color: #4CAF50;          /* 绿色背景 */\n"
"    color: white;                        /* 白色文字 */\n"
"    border: 1px solid #27ae60;           \n"
"}\n"
"\n"
"/* 悬停效果 */\n"
"QRadioButton:hover {\n"
"    background-color: #e0e0e0;\n"
"}\n"
"QRadioButton:checked:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 0px;                       /* 隐藏默认的指示器（小圆圈） */\n"
"    height: 0px;\n"
"}")
        self.radioButton_12.setObjectName("radioButton_12")
        self.horizontalLayout_3.addWidget(self.radioButton_12)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(5, 1)
        self.verticalLayout.setStretch(6, 1)
        self.verticalLayout.setStretch(7, 1)
        self.verticalLayout.setStretch(8, 1)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(301, 191))
        self.label_2.setMaximumSize(QtCore.QSize(301, 191))
        self.label_2.setStyleSheet("border-image: url(:/icon/language_illustration.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.pushButton_language_pply = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_language_pply.sizePolicy().hasHeightForWidth())
        self.pushButton_language_pply.setSizePolicy(sizePolicy)
        self.pushButton_language_pply.setMinimumSize(QtCore.QSize(121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_language_pply.setFont(font)
        self.pushButton_language_pply.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    padding: 5px 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #27ae60;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1e8449;\n"
"}")
        self.pushButton_language_pply.setObjectName("pushButton_language_pply")
        self.horizontalLayout_4.addWidget(self.pushButton_language_pply)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem8 = QtWidgets.QSpacerItem(20, 98, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 6)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "语言选择"))
        self.label_4.setText(_translate("MainWindow", "选择界面语言"))
        self.label_5.setText(_translate("MainWindow", "选择一种语言应用于整个界面"))
        self.radioButton.setText(_translate("MainWindow", "简体中文"))
        self.radioButton_8.setText(_translate("MainWindow", "繁體中文"))
        self.radioButton_3.setText(_translate("MainWindow", "English"))
        self.radioButton_9.setText(_translate("MainWindow", "日本語"))
        self.radioButton_11.setText(_translate("MainWindow", "한국어"))
        self.radioButton_10.setText(_translate("MainWindow", "Deutsch"))
        self.radioButton_12.setText(_translate("MainWindow", "Français"))
        self.pushButton_language_pply.setText(_translate("MainWindow", "应用"))
import drawable_rc
