# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\zr\miketee4(1200)\ui_1080\manager_keyboard_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(608, 574)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setMinimumSize(QtCore.QSize(70, 0))
        self.label_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setMinimumSize(QtCore.QSize(35, 35))
        self.label.setMaximumSize(QtCore.QSize(35, 35))
        self.label.setStyleSheet("border-image:url(:/icon/icon_manager_horn.png);\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setStyleSheet("QWidget#widget_3{\n"
"    background-color:white;\n"
"    border: 1px solid rgb(241, 241, 241);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    background-color:white;\n"
"    border: 2px solid rgb(44, 159, 97);\n"
"    border-radius:10px;\n"
"    color:rgb(51, 51, 51);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(44, 159, 97);\n"
"    border-radius:10px;\n"
"    color:white;\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setContentsMargins(27, 27, 27, 24)
        self.gridLayout.setSpacing(22)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_50 = QtWidgets.QPushButton(self.widget_3)
        self.btn_50.setMinimumSize(QtCore.QSize(170, 80))
        self.btn_50.setMaximumSize(QtCore.QSize(170, 80))
        self.btn_50.setStyleSheet("")
        self.btn_50.setObjectName("btn_50")
        self.gridLayout.addWidget(self.btn_50, 0, 0, 1, 1)
        self.btn_10 = QtWidgets.QPushButton(self.widget_3)
        self.btn_10.setMinimumSize(QtCore.QSize(170, 80))
        self.btn_10.setMaximumSize(QtCore.QSize(170, 80))
        self.btn_10.setStyleSheet("")
        self.btn_10.setObjectName("btn_10")
        self.gridLayout.addWidget(self.btn_10, 0, 1, 1, 1)
        self.btn_20 = QtWidgets.QPushButton(self.widget_3)
        self.btn_20.setMinimumSize(QtCore.QSize(170, 80))
        self.btn_20.setMaximumSize(QtCore.QSize(170, 80))
        self.btn_20.setObjectName("btn_20")
        self.gridLayout.addWidget(self.btn_20, 0, 2, 1, 1)
        self.btn_1 = QtWidgets.QPushButton(self.widget_3)
        self.btn_1.setMinimumSize(QtCore.QSize(170, 80))
        self.btn_1.setMaximumSize(QtCore.QSize(170, 80))
        self.btn_1.setObjectName("btn_1")
        self.gridLayout.addWidget(self.btn_1, 1, 0, 1, 1)
        self.btn_2 = QtWidgets.QPushButton(self.widget_3)
        self.btn_2.setMinimumSize(QtCore.QSize(170, 80))
        self.btn_2.setMaximumSize(QtCore.QSize(170, 80))
        self.btn_2.setObjectName("btn_2")
        self.gridLayout.addWidget(self.btn_2, 1, 1, 1, 1)
        self.btn_3 = QtWidgets.QPushButton(self.widget_3)
        self.btn_3.setMinimumSize(QtCore.QSize(170, 80))
        self.btn_3.setMaximumSize(QtCore.QSize(170, 80))
        self.btn_3.setObjectName("btn_3")
        self.gridLayout.addWidget(self.btn_3, 1, 2, 1, 1)
        self.btn_4 = QtWidgets.QPushButton(self.widget_3)
        self.btn_4.setMinimumSize(QtCore.QSize(170, 80))
        self.btn_4.setMaximumSize(QtCore.QSize(170, 80))
        self.btn_4.setObjectName("btn_4")
        self.gridLayout.addWidget(self.btn_4, 2, 0, 1, 1)
        self.btn_5_5 = QtWidgets.QPushButton(self.widget_3)
        self.btn_5_5.setMinimumSize(QtCore.QSize(170, 80))
        self.btn_5_5.setMaximumSize(QtCore.QSize(170, 80))
        self.btn_5_5.setObjectName("btn_5_5")
        self.gridLayout.addWidget(self.btn_5_5, 2, 1, 1, 1)
        self.btn_6 = QtWidgets.QPushButton(self.widget_3)
        self.btn_6.setMinimumSize(QtCore.QSize(170, 80))
        self.btn_6.setMaximumSize(QtCore.QSize(170, 80))
        self.btn_6.setObjectName("btn_6")
        self.gridLayout.addWidget(self.btn_6, 2, 2, 1, 1)
        self.btn_7 = QtWidgets.QPushButton(self.widget_3)
        self.btn_7.setMinimumSize(QtCore.QSize(170, 80))
        self.btn_7.setMaximumSize(QtCore.QSize(170, 80))
        self.btn_7.setObjectName("btn_7")
        self.gridLayout.addWidget(self.btn_7, 3, 0, 1, 1)
        self.btn_8 = QtWidgets.QPushButton(self.widget_3)
        self.btn_8.setMinimumSize(QtCore.QSize(170, 80))
        self.btn_8.setMaximumSize(QtCore.QSize(170, 80))
        self.btn_8.setObjectName("btn_8")
        self.gridLayout.addWidget(self.btn_8, 3, 1, 1, 1)
        self.btn_9 = QtWidgets.QPushButton(self.widget_3)
        self.btn_9.setMinimumSize(QtCore.QSize(170, 80))
        self.btn_9.setMaximumSize(QtCore.QSize(170, 80))
        self.btn_9.setObjectName("btn_9")
        self.gridLayout.addWidget(self.btn_9, 3, 2, 1, 1)
        self.btn_clear = QtWidgets.QPushButton(self.widget_3)
        self.btn_clear.setMinimumSize(QtCore.QSize(170, 80))
        self.btn_clear.setMaximumSize(QtCore.QSize(170, 80))
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout.addWidget(self.btn_clear, 4, 0, 1, 1)
        self.btn_0 = QtWidgets.QPushButton(self.widget_3)
        self.btn_0.setMinimumSize(QtCore.QSize(170, 80))
        self.btn_0.setMaximumSize(QtCore.QSize(170, 80))
        self.btn_0.setObjectName("btn_0")
        self.gridLayout.addWidget(self.btn_0, 4, 1, 1, 1)
        self.btn_ok = QtWidgets.QPushButton(self.widget_3)
        self.btn_ok.setMinimumSize(QtCore.QSize(170, 80))
        self.btn_ok.setMaximumSize(QtCore.QSize(170, 80))
        self.btn_ok.setObjectName("btn_ok")
        self.gridLayout.addWidget(self.btn_ok, 4, 2, 1, 1)
        self.verticalLayout.addWidget(self.widget_3)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 30)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_50.setText(_translate("Form", "50"))
        self.btn_10.setText(_translate("Form", "10"))
        self.btn_20.setText(_translate("Form", "20"))
        self.btn_1.setText(_translate("Form", "1"))
        self.btn_2.setText(_translate("Form", "2"))
        self.btn_3.setText(_translate("Form", "3"))
        self.btn_4.setText(_translate("Form", "4"))
        self.btn_5_5.setText(_translate("Form", "5"))
        self.btn_6.setText(_translate("Form", "6"))
        self.btn_7.setText(_translate("Form", "7"))
        self.btn_8.setText(_translate("Form", "8"))
        self.btn_9.setText(_translate("Form", "9"))
        self.btn_clear.setText(_translate("Form", "清空"))
        self.btn_0.setText(_translate("Form", "0"))
        self.btn_ok.setText(_translate("Form", "确定"))
import drawable_rc
