# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\zr\miketee4(1200)\ui_1080\menu_card_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(410, 292)
        Form.setMinimumSize(QtCore.QSize(410, 292))
        Form.setMaximumSize(QtCore.QSize(410, 292))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("QWidget#widget{\n"
"    border-image: url(:/icon/ic_menu_card_background_1.png);\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 37)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setStyleSheet("QWidget#widget_4{\n"
"    background-color:transparent;\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setContentsMargins(31, 16, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_widget = QtWidgets.QWidget(self.widget_4)
        self.label_widget.setMinimumSize(QtCore.QSize(136, 40))
        self.label_widget.setMaximumSize(QtCore.QSize(136, 40))
        self.label_widget.setStyleSheet("QWidget#label_widget{\n"
"    background-color:rgb(60, 211, 130);\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius:19px;\n"
"    \n"
"}")
        self.label_widget.setObjectName("label_widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.label_widget)
        self.horizontalLayout_4.setContentsMargins(28, 0, 12, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_1 = QtWidgets.QLabel(self.label_widget)
        self.label_1.setStyleSheet("color:white;")
        self.label_1.setObjectName("label_1")
        self.horizontalLayout_4.addWidget(self.label_1)
        self.label_number = QtWidgets.QLabel(self.label_widget)
        self.label_number.setMinimumSize(QtCore.QSize(20, 20))
        self.label_number.setMaximumSize(QtCore.QSize(20, 20))
        self.label_number.setStyleSheet("background-color:rgb(220, 90, 89);\n"
"border-radius:10px;\n"
"color:white;")
        self.label_number.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number.setObjectName("label_number")
        self.horizontalLayout_4.addWidget(self.label_number)
        self.horizontalLayout_3.addWidget(self.label_widget)
        spacerItem = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.widget_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 178, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout.setContentsMargins(31, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tee_name_l = QtWidgets.QLabel(self.widget_5)
        self.tee_name_l.setStyleSheet("color:rgb(51, 51, 51);")
        self.tee_name_l.setObjectName("tee_name_l")
        self.verticalLayout.addWidget(self.tee_name_l)
        self.tee_money_l = QtWidgets.QLabel(self.widget_5)
        self.tee_money_l.setStyleSheet("color:rgb(51, 51, 51);")
        self.tee_money_l.setObjectName("tee_money_l")
        self.verticalLayout.addWidget(self.tee_money_l)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.menu_tee_image = QtWidgets.QLabel(self.widget_3)
        self.menu_tee_image.setText("")
        self.menu_tee_image.setObjectName("menu_tee_image")
        self.horizontalLayout_5.addWidget(self.menu_tee_image)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.widget)
        
        # self.btn_close = QtWidgets.QToolButton(self.widget)
        # self.btn_close.setIcon(QtGui.QIcon(":/icon/icon_close.png"))
        # self.btn_close.setIconSize(QtCore.QSize(36, 36))
        # self.btn_close.setAutoRaise(True)self.btn_close = QtWidgets.QToolButton(self.widget)
        # self.btn_close.setStyleSheet("QToolButton{border:none;background:transparent;}")

        # self._overlay = QtWidgets.QWidget(self.widget)
        # self._overlay.setAttribute(QtCore.Qt.WA_TransparentForMouseEvents, False)
        # self._overlay.setGeometry(QtCore.QRect(0, 0, 410, 60))  # 覆盖卡片顶部一带
        # lo = QtWidgets.QHBoxLayout(self._overlay)
        # lo.setContentsMargins(0, 10, 10, 0)   # 右上角留 10px
        # lo.addStretch(1)
        # lo.addWidget(self.btn_close)
        # self._overlay.raise_()
        # 覆盖式关闭按钮：挂在根部 Form 上，绝对定位，不受任何内层布局边距影响
        self.btn_close = QtWidgets.QToolButton(Form)  # ★ 关键：挂在 Form，而不是 self.widget
        self.btn_close.setIcon(QtGui.QIcon(":/icon/icon_close.png"))
        self.btn_close.setFixedSize(30, 30)                 # 按钮本体尺寸
        self.btn_close.setIconSize(QtCore.QSize(30, 30))    # 图标尺寸
        self.btn_close.setAutoRaise(True)
        self.btn_close.setStyleSheet(
        "QToolButton{border:none;background:transparent;padding:0;margin:0;}"
        )
        self.btn_close.raise_()  # 确保在最上层

        # 右上角定位（留 6px 内边距，想更贴边可改小）
        def _place_close():
                m = 4
                self.btn_close.move(Form.width() - self.btn_close.width() - m, -1)

        _place_close()

        # 跟随卡片尺寸变化时重定位
        _old_resize = Form.resizeEvent if hasattr(Form, "resizeEvent") else None
        def _resize_event(ev):
                _place_close()
                if callable(_old_resize):
                        _old_resize(ev)
        Form.resizeEvent = _resize_event


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_1.setText(_translate("Form", "规格"))
        self.label_number.setText(_translate("Form", "1"))
        self.tee_name_l.setText(_translate("Form", "杨枝甘露"))
        self.tee_money_l.setText(_translate("Form", "￥22.00"))
import drawable_rc
