# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_1080\order_dialog_1_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        Form.setMinimumSize(QtCore.QSize(1920, 1080))
        Form.setMaximumSize(QtCore.QSize(1920, 1080))
        Form.setStyleSheet("QWidget#main_widget{\n"
"    background-color: rgba(255, 255, 255, 150);\n"
"}\n"
"")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.main_widget = QtWidgets.QWidget(Form)
        self.main_widget.setMaximumSize(QtCore.QSize(1920, 1080))
        self.main_widget.setObjectName("main_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(457, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.widget_5 = QtWidgets.QWidget(self.main_widget)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 372, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.widget = QtWidgets.QWidget(self.widget_5)
        self.widget.setMinimumSize(QtCore.QSize(1000, 450))
        self.widget.setMaximumSize(QtCore.QSize(1000, 450))
        self.widget.setStyleSheet("QWidget#widget{\n"
"    border-image: url(:/icon/order_dialog_background_2.png);\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(33, 21, 27, 0)
        self.horizontalLayout_2.setSpacing(14)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.order_number_l = QtWidgets.QLabel(self.widget_2)
        self.order_number_l.setStyleSheet("color:rgb(44, 159, 97);")
        self.order_number_l.setObjectName("order_number_l")
        self.horizontalLayout_2.addWidget(self.order_number_l)
        self.order_name_l = QtWidgets.QLabel(self.widget_2)
        self.order_name_l.setStyleSheet("color:rgb(44, 159, 97);")
        self.order_name_l.setObjectName("order_name_l")
        self.horizontalLayout_2.addWidget(self.order_name_l)
        spacerItem2 = QtWidgets.QSpacerItem(690, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.dialog_close_btn = QtWidgets.QPushButton(self.widget_2)
        self.dialog_close_btn.setMinimumSize(QtCore.QSize(40, 40))
        self.dialog_close_btn.setMaximumSize(QtCore.QSize(40, 40))
        self.dialog_close_btn.setStyleSheet("border-image:url(:/icon/conduit_dialog_close_btn.png);")
        self.dialog_close_btn.setText("")
        self.dialog_close_btn.setObjectName("dialog_close_btn")
        self.horizontalLayout_2.addWidget(self.dialog_close_btn)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(60, 85, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.progressBar = QtWidgets.QProgressBar(self.widget_3)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 40))
        self.progressBar.setMaximumSize(QtCore.QSize(5000, 40))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    color:white;\n"
"    border-radius:20px;\n"
"    background-color:rgb(179, 226, 197);\n"
"    text-align:center;\n"
"}\n"
"QProgressBar::chunk{\n"
"    \n"
"    border-radius:20px;            \n"
"    background-color:rgb(44, 159, 97);\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(320, 182))
        self.label_2.setStyleSheet("\n"
"border-image: url(:/icon/order_dialog_no_touch.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setContentsMargins(150, 0, 150, 50)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.order_cancel_btn = QtWidgets.QPushButton(self.widget_4)
        self.order_cancel_btn.setMinimumSize(QtCore.QSize(250, 66))
        self.order_cancel_btn.setMaximumSize(QtCore.QSize(250, 66))
        self.order_cancel_btn.setStyleSheet("QPushButton#order_cancel_btn{\n"
"    background-color:rgb(243, 243, 243);\n"
"    border: 1px solid white;\n"
"    border-radius:33px;\n"
"    color:rgb(44, 159, 97);\n"
"}\n"
"QPushButton#order_cancel_btn:pressed{\n"
"    background-color:red;\n"
"    border: 1px solid rgb(44, 159, 97);\n"
"    border-radius:33px;\n"
"    color:white;\n"
"}")
        self.order_cancel_btn.setObjectName("order_cancel_btn")
        self.horizontalLayout_3.addWidget(self.order_cancel_btn)
        spacerItem4 = QtWidgets.QSpacerItem(55, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.order_complete_btn = QtWidgets.QPushButton(self.widget_4)
        self.order_complete_btn.setMinimumSize(QtCore.QSize(250, 66))
        self.order_complete_btn.setMaximumSize(QtCore.QSize(250, 66))
        self.order_complete_btn.setStyleSheet("QPushButton#order_complete_btn{\n"
"    background-color:rgb(44, 159, 97);\n"
"    border: 1px solid rgb(44, 159, 97);\n"
"    border-radius:33px;\n"
"    color:white;\n"
"}\n"
"QPushButton#order_complete_btn:pressed{\n"
"    background-color:white;\n"
"    border: 1px solid white;\n"
"    border-radius:33px;\n"
"    color:rgb(44, 159, 97);\n"
"}")
        self.order_complete_btn.setObjectName("order_complete_btn")
        self.horizontalLayout_3.addWidget(self.order_complete_btn)
        self.verticalLayout.addWidget(self.widget_4)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 6)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout_2.addWidget(self.widget)
        spacerItem5 = QtWidgets.QSpacerItem(20, 372, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout.addWidget(self.widget_5)
        spacerItem6 = QtWidgets.QSpacerItem(457, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem6)
        self.horizontalLayout_5.addWidget(self.main_widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.order_number_l.setText(_translate("Form", "006号"))
        self.order_name_l.setText(_translate("Form", "杨枝甘露"))
        self.order_cancel_btn.setText(_translate("Form", "取消"))
        self.order_complete_btn.setText(_translate("Form", "制作完成"))
import drawable_rc
