# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\zr\miketee4(1200)\ui_1080\order_card_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(270, 150)
        Form.setMinimumSize(QtCore.QSize(270, 150))
        Form.setMaximumSize(QtCore.QSize(270, 150))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(270, 150))
        self.widget.setMaximumSize(QtCore.QSize(270, 150))
        self.widget.setStyleSheet("QWidget#widget{\n"
"    background-color:rgb(236, 253, 239);\n"
"    border-bottom: 1px solid rgb(44, 159, 97, 0.2);\n"
"    border-radius:20px;\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_2.setStyleSheet("QWidget#widget_2{\n"
"    border-bottom: 2px solid rgb(255, 255, 255);\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setMinimumSize(QtCore.QSize(81, 0))
        self.label.setMaximumSize(QtCore.QSize(81, 16777215))
        self.label.setStyleSheet("color:rgb(44, 159, 97);")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.l_order_number = QtWidgets.QLabel(self.widget_2)
        self.l_order_number.setStyleSheet("color:rgb(44, 159, 97);")
        self.l_order_number.setObjectName("l_order_number")
        self.horizontalLayout_2.addWidget(self.l_order_number)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setContentsMargins(-1, -1, 20, -1)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setStyleSheet("QWidget#widget_4{\n"
"    background-color:transparent;\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.l_name = QtWidgets.QLabel(self.widget_4)
        self.l_name.setObjectName("l_name")
        self.horizontalLayout_3.addWidget(self.l_name)
        spacerItem = QtWidgets.QSpacerItem(182, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.l_number = QtWidgets.QLabel(self.widget_4)
        self.l_number.setStyleSheet("color:rgb(44, 159, 97);")
        self.l_number.setObjectName("l_number")
        self.horizontalLayout_3.addWidget(self.l_number)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(188, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_4 = QtWidgets.QLabel(self.widget_5)
        self.label_4.setStyleSheet("color:rgb(44, 159, 97);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.l_price = QtWidgets.QLabel(self.widget_5)
        self.l_price.setStyleSheet("color:rgb(44, 159, 97);")
        self.l_price.setObjectName("l_price")
        self.horizontalLayout_4.addWidget(self.l_price)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.verticalLayout.addWidget(self.widget_3)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "订单号："))
        self.l_order_number.setText(_translate("Form", "23356"))
        self.l_name.setText(_translate("Form", "TextLabel"))
        self.l_number.setText(_translate("Form", "*1"))
        self.label_4.setText(_translate("Form", "实付："))
        self.l_price.setText(_translate("Form", "￥15"))
