# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\zr\miketee4(1200)\ui_1080\order_dialog_2_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        Form.setMinimumSize(QtCore.QSize(1920, 1080))
        Form.setMaximumSize(QtCore.QSize(1920, 1080))
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.main_widget = QtWidgets.QWidget(Form)
        self.main_widget.setStyleSheet("QWidget#main_widget{\n"
"    background-color: rgba(255, 255, 255, 150);\n"
"}\n"
"")
        self.main_widget.setObjectName("main_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(433, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.widget_5 = QtWidgets.QWidget(self.main_widget)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 348, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.widget = QtWidgets.QWidget(self.widget_5)
        self.widget.setMinimumSize(QtCore.QSize(1000, 330))
        self.widget.setMaximumSize(QtCore.QSize(1000, 330))
        self.widget.setStyleSheet("QWidget#widget{\n"
"    border-image: url(:/icon/order_dialog_background_2.png);\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 21, 27, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(690, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.dialog_close_btn = QtWidgets.QPushButton(self.widget_2)
        self.dialog_close_btn.setMinimumSize(QtCore.QSize(40, 40))
        self.dialog_close_btn.setMaximumSize(QtCore.QSize(40, 40))
        self.dialog_close_btn.setStyleSheet("border-image:url(:/icon/conduit_dialog_close_btn.png);")
        self.dialog_close_btn.setText("")
        self.dialog_close_btn.setObjectName("dialog_close_btn")
        self.horizontalLayout_2.addWidget(self.dialog_close_btn)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setContentsMargins(150, 40, -1, 68)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setMinimumSize(QtCore.QSize(45, 45))
        self.label.setMaximumSize(QtCore.QSize(45, 45))
        self.label.setStyleSheet("border-image:url(:/icon/order_dialog_warn.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.warn_msg_l = QtWidgets.QLabel(self.widget_3)
        self.warn_msg_l.setStyleSheet("color:rgb(44, 159, 97);")
        self.warn_msg_l.setText("")
        self.warn_msg_l.setObjectName("warn_msg_l")
        self.horizontalLayout_4.addWidget(self.warn_msg_l)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setContentsMargins(150, 0, 150, 50)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.order_cancel_btn = QtWidgets.QPushButton(self.widget_4)
        self.order_cancel_btn.setMinimumSize(QtCore.QSize(250, 66))
        self.order_cancel_btn.setMaximumSize(QtCore.QSize(250, 66))
        self.order_cancel_btn.setStyleSheet("QPushButton#order_cancel_btn{\n"
"    background-color:rgb(243, 243, 243);\n"
"    border: 1px solid white;\n"
"    border-radius:33px;\n"
"    color:rgb(44, 159, 97);\n"
"}\n"
"QPushButton#order_cancel_btn:pressed{\n"
"    background-color:red;\n"
"    border: 1px solid rgb(44, 159, 97);\n"
"    border-radius:33px;\n"
"    color:white;\n"
"}")
        self.order_cancel_btn.setObjectName("order_cancel_btn")
        self.horizontalLayout_3.addWidget(self.order_cancel_btn)
        spacerItem3 = QtWidgets.QSpacerItem(55, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.order_supple_material_btn = QtWidgets.QPushButton(self.widget_4)
        self.order_supple_material_btn.setMinimumSize(QtCore.QSize(250, 66))
        self.order_supple_material_btn.setMaximumSize(QtCore.QSize(250, 66))
        self.order_supple_material_btn.setStyleSheet("QPushButton#order_supple_material_btn{\n"
"    background-color:rgb(44, 159, 97);\n"
"    border: 1px solid rgb(44, 159, 97);\n"
"    border-radius:33px;\n"
"    color:white;\n"
"}\n"
"QPushButton#order_supple_material_btn:pressed{\n"
"    background-color:white;\n"
"    border: 1px solid white;\n"
"    border-radius:33px;\n"
"    color:rgb(44, 159, 97);\n"
"}")
        self.order_supple_material_btn.setObjectName("order_supple_material_btn")
        self.horizontalLayout_3.addWidget(self.order_supple_material_btn)
        self.verticalLayout.addWidget(self.widget_4)
        self.verticalLayout_2.addWidget(self.widget)
        spacerItem4 = QtWidgets.QSpacerItem(20, 348, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout.addWidget(self.widget_5)
        spacerItem5 = QtWidgets.QSpacerItem(433, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.horizontalLayout_5.addWidget(self.main_widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.order_cancel_btn.setText(_translate("Form", "稍后再说"))
        self.order_supple_material_btn.setText(_translate("Form", "去补料"))
import drawable_rc
