# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\zr\miketee4(1200)\ui_1080\outtee_notice_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(584, 943)
        Form.setMinimumSize(QtCore.QSize(584, 943))
        Form.setMaximumSize(QtCore.QSize(584, 943))
        Form.setStyleSheet("QWidget#Form{\n"
"    background-color:white;\n"
"    border-radius:10px;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setStyleSheet("QScrollBar{\n"
"    background-color:black;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    background-color: white;\n"
"    height: 9px;\n"
"    padding-right: 1px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background-color: rgb(187, 242, 212);\n"
"    width: 10px;\n"
"    padding-bottom: 0px;    \n"
"    padding-top: 0px;\n"
"}\n"
"QScrollBar::groove {\n"
"    background: rgb(82, 83, 86);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle {\n"
"    background: blue;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    border:1px solid rgb(42, 47, 85);\n"
"    border-radius: 3px;\n"
"    background-color: rgb(82, 83, 86);\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color:rgb(82, 83, 86);\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    border:1px solid rgb(44, 159, 97,0.3);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(44, 159, 97,0.3);\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color:rgb(58, 209, 126);\n"
"}\n"
" QScrollBar::sub-line:vertical, QScrollBar::add-line:vertical {\n"
"            height: 0px;\n"
"            subcontrol-origin: margin;\n"
"        }")
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.content = QtWidgets.QWidget()
        self.content.setGeometry(QtCore.QRect(0, 0, 582, 941))
        self.content.setStyleSheet("QWidget#content{\n"
"    background-color:white;\n"
"    border-radius:10px;\n"
"}")
        self.content.setObjectName("content")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.content)
        self.verticalLayout.setObjectName("verticalLayout")
        self.content_list_widget = QtWidgets.QWidget(self.content)
        self.content_list_widget.setObjectName("content_list_widget")
        self.verticalLayout.addWidget(self.content_list_widget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.content)
        self.horizontalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
